### ISSUE TITLE
Notification icon not indicating new messages and the icon itself is a bit off

### ISSUE THREAD

**Issue by pingtaoye** [willianmano/moodle-theme_moove#107] opened 2018-07-25 18:33 UTC
In the latest version of this theme, the notification icon is displayed a bit off on all pages except the dashboard and it is not indicating new messages from other users as it was on 2.3.2 version.
![course online clb 4 6 master](https://user-images.githubusercontent.com/17863517/43220322-97f73cde-8ffe-11e8-850e-4b90d299a336.jpg)
![dashboard](https://user-images.githubusercontent.com/17863517/43220324-99408a6e-8ffe-11e8-9553-f7c5d6ba2bc2.jpg)

**Comment by willianmano** [comment] 2018-08-02 11:40
@pingtaoye I tested all pages and everything works well. I could not able to simulate this error.

**Comment by janisfiss** [comment] 2018-08-07 16:50
I have the same issues that Ping reported. In my test site, the notification icon showed that there were new messages but in my live site (with Moove 2.3.4) it no longer shows that. I have to constantly click on the icon to check for messages. 
As well, the icon is out of alignment in my admin account - same as the image that Ping posted. This only seems to affect my admin account though so I'm not so worried about that.

**Comment by willianmano** [comment] 2018-08-09 11:15
@janisfiss and @pingtaoye could you please try to change the theme to Boost? Ff the error persists it's a Moodle problem otherwise it's a Moove issue.

**Comment by pingtaoye** [comment] 2018-08-22 18:29
@willianmano The issue is not happening in Boost.

**Comment by MohamedBRH** [comment] 2018-09-03 16:39
Same here, I tested many themes ,the problem occurs when I activate Moove.
any solutions ?

**Comment by MohamedSR** [comment] 2018-09-06 10:34
so how to solve this problem ? <div class="count-container hidden" data-region="count-container"></div> the counter doesn't change when recived a message

**Comment by SubjectXXX** [comment] 2018-09-17 07:57
@willianmano Can we get confirmation that this is the culprit solution?

**Comment by mkozmelj** [comment] 2018-09-19 07:01
@SubjectXXX it is working with theme Moove 2.3.6  and Moodle 3.5.2

**Comment by SubjectXXX** [comment] 2018-09-20 07:06
It is still not fixed in version 2.3.8, thus keeping the workaround from MohamerSR, BUT this introduces new bug with displaying notification icon with number 0 in it if you click on message balloon and click elsewhere to close this messages popup.

**Comment by wafa123** [comment] 2018-10-02 08:49
> 
> 
> i solved it : in moove/template/message_popup/message_popover.mustache {{unreadcount}} is missing so add {{unreadcount}} to the div with data-region="count-container" attribute and {{^unreadcount}}hidden{{/unreadcount}} in class
> 
> some thing for notification

please show me how to fix it i tried but with no use please send me the modified file if you can

**Comment by rafaelpbaptista** [comment] 2018-10-02 16:34
Up

**Comment by rafaelpbaptista** [comment] 2018-11-12 21:35
@willianmano, estamos precisando muito resolver esse problema. Já fizemos o teste com o tema Boost como você sugeriu e o problema não acontece. Está ocorrendo só no Moove mesmo. Obrigado!

**Comment by janisfiss** [comment] 2018-11-13 17:05
We are also still having this problem in Moove. We tested with Boost and the notifications worked as expected. (Getting lots of complaints from teachers!)

**Comment by valeriia-s** [comment] 2018-12-18 19:18
@willianmano It's been a month, do you have any updates for us? Do you need any information to reproduce the issue?

**Comment by ak4t0sh** [comment] 2019-01-21 17:53
fixed in PR #136

**Comment by janisfiss** [comment] 2019-01-22 19:35
Thanks for fixing this! I can now see new message notifications with the message icon. (Alignment is still off but I can live with that.)

**Comment by ak4t0sh** [comment] 2019-01-23 07:09
Alignment issue seems caused by [_navbar.scss#L191](https://github.com/willianmano/moodle-theme_moove/blob/29bd1b21e39603f9493917a729c27e26ab299eba/scss/moove/_navbar.scss#L191). Remove this line and it should be OK. (Works on my moodles)
Before removal : 
![image](https://user-images.githubusercontent.com/2222386/51588928-bf757200-1ee5-11e9-98e9-d62d442f8cc7.png)
After : 
![image](https://user-images.githubusercontent.com/2222386/51588973-dcaa4080-1ee5-11e9-86b5-bca588536018.png)

@willianmano could you apply the change when merging #136 ordo you want me to do a new PR for this fix ?

**Closed** 2022-06-15 06:16 UTC
