### ISSUE TITLE
Unexpected behavior editing a quiz as a teacher

### ISSUE THREAD

**Issue by albertverges** [willianmano/moodle-theme_moove#323] opened 2021-07-18 19:45 UTC
When a course is configured with a future start date. If you create a new quiz and then, as a teacher, you click on the quiz name to edit it, the  edit menu (a gear on the top right corner) does'nt appear. 

![image](https://user-images.githubusercontent.com/72107099/126080178-9ab450df-8ab6-4265-b241-73f5e98f4b99.png)

Admin user don't have this behavior, he sees the gear menu. Changing to Boost theme teachers can see the gear menu too.

This issue can be reproduced on a blank moodle 3.11 installation.

The workaround is easy, simply change the course start date to a past date and teachers will see the gear menu.  But, sometimes is usefull for teachers to prepare courses before the course began and they need to access the gear menu.

Contact me if you need more information. I'll try to help.

**Comment by izendegi** [comment] 2021-07-29 10:25
Hi, we can also reproduce this issue on our Moodle 3.11 installation, and the workaround also works for us, thank you @albertverges !

**Comment by jbreitenbucher** [comment] 2021-08-10 17:01
Same issue. However, changing the start date is not an option for us. What is the real fix for this?

**Comment by jbreitenbucher** [comment] 2021-08-18 14:33
On further testing changing the start date does not make the cog visible to teachers for us.

**Comment by Kzou** [comment] 2021-09-14 14:59
Hello,
the problem occurs when a teacher does a review. Then the cog disappears and we can't edit the test.
Moove version 3.11.05

**Comment by kaceli** [comment] 2021-11-03 20:07
I think we found the solution. It seems to have to do with the end date in the course. Changing the end date for the courses seems to do the trick. 

We used PHPmyAdmin to update them in bulk. 

Thanks for the pointer adamjenkins and philip-daoud.

**Comment by SubjectXXX** [comment] 2021-11-15 12:25
Can confirm, that course being ended is the culprit.

**Comment by rene-van-dijk** [comment] 2021-11-27 12:05
We have a similar issue with the Moodle Quiz Activities cogwheel not displaying to a Teacher: changing the course start date or entering a course end date or both did not work. Any suggestions?

**Comment by robindv** [comment] 2021-12-04 10:24
Looks like a duplicate of #330, which is fixed now on the master branch since c32e5c909026b7084835a4bdbc9411c1cd6ede82
Perhaps @willianmano can release a new version.

**Comment by willianmano** [comment] 2022-06-15 06:15
Sorry, I only support the current major version of Moodle, which is 4.0.

**Closed by willianmano** 2022-06-15 06:15 UTC
